# Generated by Django 5.2.4 on 2025-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('jn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('teamname', models.CharField(max_length=100)),
            ],
        ),
    ]
